In [1]:
# NumPy(numerical python) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지

import numpy as np

# 1차원 배열
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

# 2차원 배열
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])     # 1행 3열인 2차원 배열. 차이점은 [[]]
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))



array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원


In [5]:
# ndarray의 데이터 타입
# ndarray내의 데이터 타입은 같은 데이터 타입만 가능

list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

# 다른 데이터 유형이 섞여 있는 리스트를 ndarray 변환 시 더 큰 데이터 타입으로 형 변환
list2=[1,2,'test']    # 문자열의 데이터 타입이 더 크므로 1은 '1'로 형 변환
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]    # 마찬가지로 실수형이 더 크므로 1이 1.0으로 변한다.
array3=np.array(list3)
print(array3,array3.dtype)

# list3 같은 경우 1,2 를 실수형으로 변환하는 것은 낭비임
# 고로 3.0을 정수 타입으로 변환하는 것이 메모리 절약에 도움됨
# astype을 활용

array_int = np.array([1,2,3])
array_float = array_int.astype('float64')    # int를 float로
print(array_float, array_float.dtype)

array_int1=array_float.astype('int32')    # float를 int로
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])    # float를 int로
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32
['1' '2' 'test'] <U11
[1. 2. 3.] float64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [8]:
# ndarray 편리하게 생성하기
# arange, zeros, ones 활용

# arange
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

# zeros, ones
zero_array=np.zeros((3,2),dtype='int32')    # 데이터 타입 미설정 시 float형으로 초기화
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))    # 그래서 얘는 데이터 타입이 float형 ㅇㅋ?
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [15]:
# reshape()
# ndarray를 특정 차원 및 크기로 변환

array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)    # 2행 5열
print('array2:\n',array2)

array3=array1.reshape(5,2)    # 5행 2열
print('array3:\n',array3)

# 인자를 -1로 사용하는 경우
array4=array1.reshape(-1,5)    # 자동으로 조정해준다. 10개의 데이터가 있고 5개의 열을 설정하면 -1을 사용했을 때 행을 2로 설정해줌
print('array4:\n',array4)

array5=array1.reshape(5,-1)    # 마찬가지로 행이 5니까 열을 2로 설정. 참고로 low는 열 column은 행
print('array5:\n',array5)

# array6=array1.reshape(4,-1) -> 오류
# 주로 reshape(-1,1)로 자주 사용된다.

array6=np.arange(8)
array3d=array6.reshape((2,2,2))
print('array3d:\n',array3d.tolist())    # tolist: 리스트로 변환

# 3차원 ndarray를 2차원으로 변환
array7=array3d.reshape(-1,1)
print('array7:\n', array7.tolist())
print('array7 shape:', array7.shape)

# 1차원을 2차원으로 변환
array8=array6.reshape(-1,1)
print('array8:\n', array8.tolist())
print('array8 shape:', array8.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array5:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array7:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array7 shape: (8, 1)
array8:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array8 shape: (8, 1)


In [6]:
# 인덱싱 : ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함
# 1. 특정한 데이터만 추출
# 2. 슬라이싱
# 3. 팬시 인덱싱
# 4. 불린 인덱싱

# 1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
# 단일 값 추출
# 1차원

array1 = np.arange(start=1,stop=10)
print('array1:',array1)
value=array1[2]
print('value:',value)
print(type(value))
print('맨 뒤의 값:',array1[-1],' 맨 뒤에서 두 번째 값:',array1[-2])    # 배열에서 -1은 맨 마지막, -2는 마지막 앞을 의미
array1[0] = 9
array1[8] = 0
print('array1:',array1)    # 값 변경 가능

# 2차원
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:',array2d[0,0])
print('(row=0, col=1) index 가리키는 값:',array2d[0,1])
print('(row=1, col=0) index 가리키는 값:',array2d[1,0])
print('(row=2, col=2) index 가리키는 값:',array2d[2,2])



array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9  맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9
